language: go

env:
  global:
    - GO111MODULE=on

go:
  - 1.12.x

before_install:
  - build/install_protoc.sh
install: true

script:
  - PATH=${GOPATH}/bin:${PATH} make all
  - go test -race ./...

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/gopath/pkg/mod/