language: go

env:
  global:
    - GO111MODULE=on

go:
  - 1.12.x

before_install:
  - build/install_protoc.sh
install: true

script:
  - make all
  - go test -race ./...

branches:
  only:
    - master