language: go

env:
  global:
    - GO111MODULE=on

go:
  - 1.12.x

install: true

script:
  - go test -race ./...
  - make hambone

branches:
  only:
    - master

cache:
  directories:
    - /home/travis/gopath/pkg/mod/