// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hambone.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hambone struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Img                  string   `protobuf:"bytes,2,opt,name=img,proto3" json:"img,omitempty"`
	Position             string   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hambone) Reset()         { *m = Hambone{} }
func (m *Hambone) String() string { return proto.CompactTextString(m) }
func (*Hambone) ProtoMessage()    {}
func (*Hambone) Descriptor() ([]byte, []int) {
	return fileDescriptor_f035915296f34611, []int{0}
}

func (m *Hambone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hambone.Unmarshal(m, b)
}
func (m *Hambone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hambone.Marshal(b, m, deterministic)
}
func (m *Hambone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hambone.Merge(m, src)
}
func (m *Hambone) XXX_Size() int {
	return xxx_messageInfo_Hambone.Size(m)
}
func (m *Hambone) XXX_DiscardUnknown() {
	xxx_messageInfo_Hambone.DiscardUnknown(m)
}

var xxx_messageInfo_Hambone proto.InternalMessageInfo

func (m *Hambone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hambone) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *Hambone) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type GetRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f035915296f34611, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type GetResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Hambones             []*Hambone `protobuf:"bytes,2,rep,name=hambones,proto3" json:"hambones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f035915296f34611, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetResponse) GetHambones() []*Hambone {
	if m != nil {
		return m.Hambones
	}
	return nil
}

func init() {
	proto.RegisterType((*Hambone)(nil), "v1.Hambone")
	proto.RegisterType((*GetRequest)(nil), "v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "v1.GetResponse")
}

func init() { proto.RegisterFile("hambone.proto", fileDescriptor_f035915296f34611) }

var fileDescriptor_f035915296f34611 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x48, 0xcc, 0x4d,
	0xca, 0xcf, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0x92, 0x49,
	0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49,
	0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x50, 0xf2, 0xe6, 0x62, 0xf7, 0x80, 0x68, 0x11, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0x04, 0xb8, 0x98, 0x33, 0x73, 0xd3, 0x25, 0x98, 0xc0, 0x42, 0x20, 0xa6, 0x90, 0x14, 0x17, 0x47,
	0x41, 0x7e, 0x71, 0x26, 0xc8, 0x0c, 0x09, 0x66, 0xb0, 0x30, 0x9c, 0xaf, 0x24, 0xc7, 0xc5, 0xe5,
	0x9e, 0x5a, 0x12, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x02, 0xd2, 0x9b, 0x58, 0x90, 0x09, 0x35,
	0x0e, 0xc4, 0x54, 0xf2, 0xe0, 0xe2, 0x06, 0xcb, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x62, 0x2a,
	0x10, 0x52, 0xe7, 0xe2, 0x80, 0x7a, 0xa0, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x5b,
	0xaf, 0xcc, 0x50, 0x0f, 0xea, 0xc2, 0x20, 0xb8, 0xa4, 0x51, 0x18, 0x17, 0x1f, 0x54, 0x30, 0x38,
	0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x05, 0x6c, 0x36, 0x54, 0xb0, 0x58, 0x88, 0x0f, 0xa4,
	0x0f, 0xe1, 0x18, 0x29, 0x7e, 0x38, 0x1f, 0x62, 0xb9, 0x92, 0x48, 0xd3, 0xe5, 0x27, 0x93, 0x99,
	0xf8, 0x84, 0x78, 0xf4, 0xcb, 0x0c, 0xf5, 0x61, 0xe6, 0x26, 0xb1, 0x81, 0x43, 0xc5, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xcf, 0x8f, 0x61, 0x8a, 0x48, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HamboneServiceClient is the client API for HamboneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HamboneServiceClient interface {
	GetHambones(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type hamboneServiceClient struct {
	cc *grpc.ClientConn
}

func NewHamboneServiceClient(cc *grpc.ClientConn) HamboneServiceClient {
	return &hamboneServiceClient{cc}
}

func (c *hamboneServiceClient) GetHambones(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/v1.HamboneService/GetHambones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HamboneServiceServer is the server API for HamboneService service.
type HamboneServiceServer interface {
	GetHambones(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterHamboneServiceServer(s *grpc.Server, srv HamboneServiceServer) {
	s.RegisterService(&_HamboneService_serviceDesc, srv)
}

func _HamboneService_GetHambones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HamboneServiceServer).GetHambones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HamboneService/GetHambones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HamboneServiceServer).GetHambones(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HamboneService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.HamboneService",
	HandlerType: (*HamboneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHambones",
			Handler:    _HamboneService_GetHambones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hambone.proto",
}
