name: Go

on:
  pull_request:
    branches: [ master, development ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Install Protobufs
        env:
          GO111MODULE: "on"
          PROTOBUF_VERSION: "3.5.1"
        run: |
          PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
          pushd ~
          curl -L https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME} -o ${PROTOC_FILENAME}
          unzip ${PROTOC_FILENAME}
          bin/protoc --version
          popd

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.0.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get dependencies
        env:
          GO111MODULE: "on"
          PROTOBUF_VERSION: "3.5.1"
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Test
        run: go test -v .

      - name: Build Check
        env:
          GO111MODULE: "on"
          PROTOBUF_VERSION: "3.5.1"
        run: |
          export PROTOC=~/bin/protoc
          export PATH=${PATH}:~/bin
          go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
          go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
          go get -u github.com/golang/protobuf/protoc-gen-go
          go get -u github.com/grpc-ecosystem/grpc-gateway
          go get -u ./...
          make clean && make all
